// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsFCBXpWINi7bF3Bx0qQUrvWDNAs_9ydA',
    appId: '1:1034232662194:web:425417041d65f1512e61ab',
    messagingSenderId: '1034232662194',
    projectId: 'pet-app-fd9d6',
    authDomain: 'pet-app-fd9d6.firebaseapp.com',
    storageBucket: 'pet-app-fd9d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkD_bTTme64MFXSyu6CzZmy-pTwhMvyDk',
    appId: '1:1034232662194:android:53e5099cc5a5abf32e61ab',
    messagingSenderId: '1034232662194',
    projectId: 'pet-app-fd9d6',
    storageBucket: 'pet-app-fd9d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi76dX9lWNVrpUnxgKbJr5T5VBS0pDnx8',
    appId: '1:1034232662194:ios:a20b10774efbc2aa2e61ab',
    messagingSenderId: '1034232662194',
    projectId: 'pet-app-fd9d6',
    storageBucket: 'pet-app-fd9d6.appspot.com',
    iosClientId: '1034232662194-6jlbmp860p7r0ng5da0egpmgvglfpcf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi76dX9lWNVrpUnxgKbJr5T5VBS0pDnx8',
    appId: '1:1034232662194:ios:a20b10774efbc2aa2e61ab',
    messagingSenderId: '1034232662194',
    projectId: 'pet-app-fd9d6',
    storageBucket: 'pet-app-fd9d6.appspot.com',
    iosClientId: '1034232662194-6jlbmp860p7r0ng5da0egpmgvglfpcf6.apps.googleusercontent.com',
    iosBundleId: 'com.example.petApp',
  );
}
